import type { Corretor, Negocio } from "./types";

// Dados fictícios para demonstração. Os imóveis abaixo espelham anúncios
// reais do site imoveisgmbs.com.br para a apresentação ficar familiar
// ao cliente — nenhum valor aqui é lançamento real de venda.

export const corretores: Corretor[] = [
  {
    id: "c1",
    nome: "Ana Beatriz Ramos",
    email: "ana.ramos@imoveisgmbs.com.br",
    telefone: "(41) 99101-2233",
    creci: "CRECI/PR 34.211",
    comissaoPadrao: 5,
    status: "ativo",
    dataEntrada: "2025-02-10",
    iniciais: "AR",
  },
  {
    id: "c2",
    nome: "Carlos Eduardo Mota",
    email: "carlos.mota@imoveisgmbs.com.br",
    telefone: "(41) 99202-3344",
    creci: "CRECI/PR 29.884",
    comissaoPadrao: 4.5,
    status: "ativo",
    dataEntrada: "2024-08-22",
    iniciais: "CM",
  },
  {
    id: "c3",
    nome: "Fernanda Lopes",
    email: "fernanda.lopes@imoveisgmbs.com.br",
    telefone: "(41) 99303-4455",
    creci: "CRECI/PR 41.007",
    comissaoPadrao: 6,
    status: "ativo",
    dataEntrada: "2025-11-03",
    iniciais: "FL",
  },
  {
    id: "c4",
    nome: "Rodrigo Almeida",
    email: "rodrigo.almeida@imoveisgmbs.com.br",
    telefone: "(41) 99404-5566",
    creci: "CRECI/PR 27.650",
    comissaoPadrao: 4,
    status: "ativo",
    dataEntrada: "2024-03-15",
    iniciais: "RA",
  },
  {
    id: "c5",
    nome: "Juliana Prado",
    email: "juliana.prado@imoveisgmbs.com.br",
    telefone: "(41) 99505-6677",
    creci: "CRECI/PR 38.492",
    comissaoPadrao: 5,
    status: "ativo",
    dataEntrada: "2025-06-01",
    iniciais: "JP",
  },
  {
    id: "c6",
    nome: "Marcelo Tanaka",
    email: "marcelo.tanaka@imoveisgmbs.com.br",
    telefone: "(41) 99606-7788",
    creci: "CRECI/PR 22.130",
    comissaoPadrao: 4.5,
    status: "inativo",
    dataEntrada: "2023-05-18",
    iniciais: "MT",
  },
  {
    id: "c7",
    nome: "Patrícia Nunes",
    email: "patricia.nunes@imoveisgmbs.com.br",
    telefone: "(41) 99707-8899",
    creci: "CRECI/PR 44.918",
    comissaoPadrao: 5.5,
    status: "ativo",
    dataEntrada: "2026-07-01",
    iniciais: "PN",
  },
];

export const negocios: Negocio[] = [
  {
    id: "n1",
    imovel: "Casa Umbará",
    bairro: "Umbará",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 1650000,
    corretorId: "c2",
    dataFechamento: "2026-08-04",
    comissaoPercentual: 4.5,
    statusPagamento: "pendente",
  },
  {
    id: "n2",
    imovel: "Apartamento Boa Vista",
    bairro: "Boa Vista",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 739000,
    corretorId: "c1",
    dataFechamento: "2026-08-01",
    comissaoPercentual: 5,
    statusPagamento: "pendente",
  },
  {
    id: "n3",
    imovel: "Casa Xaxim",
    bairro: "Xaxim",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 449000,
    corretorId: "c3",
    dataFechamento: "2026-07-28",
    comissaoPercentual: 6,
    statusPagamento: "pendente",
  },
  {
    id: "n4",
    imovel: "Apartamento Centro",
    bairro: "Centro",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 499000,
    corretorId: "c5",
    dataFechamento: "2026-07-22",
    comissaoPercentual: 5,
    statusPagamento: "pago",
    dataPagamento: "2026-08-02",
  },
  {
    id: "n5",
    imovel: "Casa Estados",
    bairro: "Estados",
    cidade: "Fazenda Rio Grande/PR",
    tipo: "Venda",
    valorVenda: 400000,
    corretorId: "c4",
    dataFechamento: "2026-07-18",
    comissaoPercentual: 4,
    statusPagamento: "pago",
    dataPagamento: "2026-08-05",
  },
  {
    id: "n6",
    imovel: "Casa Nações",
    bairro: "Estados",
    cidade: "Fazenda Rio Grande/PR",
    tipo: "Venda",
    valorVenda: 350000,
    corretorId: "c4",
    dataFechamento: "2026-07-11",
    comissaoPercentual: 4,
    statusPagamento: "pago",
    dataPagamento: "2026-07-18",
  },
  {
    id: "n7",
    imovel: "Apartamento Jardim Amélia",
    bairro: "Jardim Amélia",
    cidade: "Pinhais/PR",
    tipo: "Venda",
    valorVenda: 320000,
    corretorId: "c7",
    dataFechamento: "2026-07-09",
    comissaoPercentual: 5.5,
    statusPagamento: "pago",
    dataPagamento: "2026-08-06",
  },
  {
    id: "n8",
    imovel: "Casa São Dimas",
    bairro: "São Dimas",
    cidade: "Colombo/PR",
    tipo: "Venda",
    valorVenda: 179900,
    corretorId: "c3",
    dataFechamento: "2026-06-30",
    comissaoPercentual: 6,
    statusPagamento: "pago",
    dataPagamento: "2026-07-07",
  },
  {
    id: "n9",
    imovel: "Sobrado Alphaville Graciosa",
    bairro: "Alphaville Graciosa",
    cidade: "Pinhais/PR",
    tipo: "Venda",
    valorVenda: 890000,
    corretorId: "c1",
    dataFechamento: "2026-06-22",
    comissaoPercentual: 5,
    statusPagamento: "pago",
    dataPagamento: "2026-06-29",
  },
  {
    id: "n10",
    imovel: "Apartamento Água Verde",
    bairro: "Água Verde",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 610000,
    corretorId: "c2",
    dataFechamento: "2026-06-14",
    comissaoPercentual: 4.5,
    statusPagamento: "pago",
    dataPagamento: "2026-06-20",
  },
  {
    id: "n11",
    imovel: "Casa Atuba",
    bairro: "Atuba",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 265000,
    corretorId: "c5",
    dataFechamento: "2026-06-05",
    comissaoPercentual: 5,
    statusPagamento: "pago",
    dataPagamento: "2026-06-12",
  },
  {
    id: "n12",
    imovel: "Cobertura Batel",
    bairro: "Batel",
    cidade: "Curitiba/PR",
    tipo: "Venda",
    valorVenda: 1180000,
    corretorId: "c6",
    dataFechamento: "2026-05-20",
    comissaoPercentual: 4.5,
    statusPagamento: "pago",
    dataPagamento: "2026-05-27",
  },
];

export function comissaoValor(n: Negocio) {
  return (n.valorVenda * n.comissaoPercentual) / 100;
}

export function corretorPorId(id: string) {
  return corretores.find((c) => c.id === id);
}

export function negociosPorCorretor(id: string) {
  return negocios.filter((n) => n.corretorId === id);
}
